### PR TITLE
Add Hero images

### PR DESCRIPTION
**Pull request by Wardormeur**
Based on Conor's images
Need review as previous commit already contains images for the Hero

### CODE REVIEW

**Comment by DanielBrierton** [comment]
Deploy preview for *cdf-website* ready!

Built with commit 2cccc87b3531da20d692bd0f7dd4f3a6e650705c

https://deploy-preview-9--cdf-website.netlify.com

**Comment by conoramurphy** [comment]
For the attribution text can we change to be the same style as "Lauren - CoderDojo Dun Laoghaire" is on the same page. And can we add 8px padding to the top of the text please. Reviewing the images now.

**Comment by conoramurphy** [comment]
@Wardormeur images look good. If you change the text as above and add in the new images I put on the trello card we should be good.

Can we rescale the images tho for faster loading? They are never seen large are they? So something like 700 ox wide seem plenty sharp for desktop and mobile? Maybe even smaller...

**Comment by Wardormeur** [comment]
Rescaling of images is in another ticket, but yes

**Pull request merged**
