### PR TITLE
Update translation link in the footer

### PR DESCRIPTION
**Pull request by niccokunzmann**
contributes to https://github.com/CoderDojo/coderdojo.com/issues/38

### CODE REVIEW

**Comment by DanielBrierton** [comment]
Deploy preview for *cdf-website* ready!

Built with commit 84d2e27a51d20e699ad7ea35598ac35f29edf06a

https://deploy-preview-39--cdf-website.netlify.com

**Comment by Wardormeur** [comment]
I'm not going to accept this PR. We can redirect from here (github) to crowdin directly because we're in communication with developer-alike. When we're reaching for non-technical, we should direct through the helpdesk to explain the process.
I don't believe that adding this step is very user friendly as well (gated participation) but that may be necessary for a first time participation of a community member (as they may not be aware of github, or how crowdin work..)

**Comment by niccokunzmann** [comment]
Thanks for your reply.

Then, I think, the issue still remains open.
If you however think that this is an improvement, you can merge it. If you like to reject, you can close the pull request. No need to keep it open, then.

**Comment by Wardormeur** [comment]
I wanted to let you the time to answer before closing it :)
Cheers,
W.

**Pull request closed without merging**
